version: '3.8'
services:
  db-tester:
    build: .
    ports:
      - "8889:8889"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    env_file: 
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Access host from container

networks:
  default:
    external: true
    name: dokploy-network
